/*
	This file is automatically generated.
	Do not edit this file manually.
*/

#include "../Include/ComponentMaps.hpp"

using namespace Fnd::EntitySystem;

ComponentMaps::ComponentMaps()
{
}

Component* ComponentMaps::GetComponent( unsigned int component_id, unsigned int index )
{
	switch (component_id)
	{
		case 0:
			return GetComponent<SceneNodeComponent>(index);
		case 1:
			return GetComponent<CameraPropertiesComponent>(index);
		case 2:
			return GetComponent<ModelComponent>(index);
		case 3:
			return GetComponent<RigidBodyComponent>(index);
		case 4:
			return GetComponent<AmbientLightComponent>(index);
		case 5:
			return GetComponent<PointLightComponent>(index);
		case 6:
			return GetComponent<DirectionalLightComponent>(index);
		case 7:
			return GetComponent<SpotLightComponent>(index);
		default:
			return nullptr;
}
}

bool ComponentMaps::RemoveComponent( Component* component )
{
	switch (component->GetComponentID())
	{
		case 0:
			return RemoveComponent( (SceneNodeComponent*)component );
		case 1:
			return RemoveComponent( (CameraPropertiesComponent*)component );
		case 2:
			return RemoveComponent( (ModelComponent*)component );
		case 3:
			return RemoveComponent( (RigidBodyComponent*)component );
		case 4:
			return RemoveComponent( (AmbientLightComponent*)component );
		case 5:
			return RemoveComponent( (PointLightComponent*)component );
		case 6:
			return RemoveComponent( (DirectionalLightComponent*)component );
		case 7:
			return RemoveComponent( (SpotLightComponent*)component );
		default:
			return false;
}
}

