/*
	This file is automatically generated.
	Do not edit this file manually.
*/

#include "../Include/Components.hpp"
#include "../Include/ComponentDataConversion.hpp"
#include "../../Utility/Include/XmlManager.hpp"

using namespace Fnd::EntitySystem;

SceneNodeComponent_s::SceneNodeComponent_s()
{
}

SceneNodeComponent_s::~SceneNodeComponent_s()
{
}

CameraPropertiesComponent_s::CameraPropertiesComponent_s()
{
}

CameraPropertiesComponent_s::~CameraPropertiesComponent_s()
{
}

ModelComponent_s::ModelComponent_s()
{
}

ModelComponent_s::~ModelComponent_s()
{
}

RigidBodyComponent_s::RigidBodyComponent_s()
{
}

RigidBodyComponent_s::~RigidBodyComponent_s()
{
}

AmbientLightComponent_s::AmbientLightComponent_s()
{
}

AmbientLightComponent_s::~AmbientLightComponent_s()
{
}

PointLightComponent_s::PointLightComponent_s()
{
}

PointLightComponent_s::~PointLightComponent_s()
{
}

DirectionalLightComponent_s::DirectionalLightComponent_s()
{
}

DirectionalLightComponent_s::~DirectionalLightComponent_s()
{
}

SpotLightComponent_s::SpotLightComponent_s()
{
}

SpotLightComponent_s::~SpotLightComponent_s()
{
}

