/*
	This file is automatically generated.
	Do not edit this file manually.
*/

#ifndef _SYSTEMNODES_HPP_
#define _SYSTEMNODES_HPP_

#include "Components.hpp"
#include "SystemNode.hpp"

namespace Fnd
{
namespace EntitySystem
{

class EntitySystem;

class SceneNodeNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			SceneNodeComponent* scenenode;
		};

		SceneNodeNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetSceneNodeComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _scenenode_id;
};

class AmbientLightNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			AmbientLightComponent* ambientlight;
		};

		AmbientLightNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetAmbientLightComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _ambientlight_id;
};

class CameraNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			SceneNodeComponent* scenenode;
			CameraPropertiesComponent* cameraproperties;
		};

		CameraNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetSceneNodeComponentId() const;

		unsigned int GetCameraPropertiesComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _scenenode_id;
		unsigned int _cameraproperties_id;
};

class ModelNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			SceneNodeComponent* scenenode;
			ModelComponent* model;
		};

		ModelNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetSceneNodeComponentId() const;

		unsigned int GetModelComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _scenenode_id;
		unsigned int _model_id;
};

class RigidBodyNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			SceneNodeComponent* scenenode;
			RigidBodyComponent* rigidbody;
		};

		RigidBodyNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetSceneNodeComponentId() const;

		unsigned int GetRigidBodyComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _scenenode_id;
		unsigned int _rigidbody_id;
};

class PointLightNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			SceneNodeComponent* scenenode;
			PointLightComponent* pointlight;
		};

		PointLightNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetSceneNodeComponentId() const;

		unsigned int GetPointLightComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _scenenode_id;
		unsigned int _pointlight_id;
};

class DirectionalLightNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			SceneNodeComponent* scenenode;
			DirectionalLightComponent* directionallight;
		};

		DirectionalLightNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetSceneNodeComponentId() const;

		unsigned int GetDirectionalLightComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _scenenode_id;
		unsigned int _directionallight_id;
};

class SpotLightNode:
	public Fnd::EntitySystem::SystemNode
{
	public:

		struct Pointers
		{
			SceneNodeComponent* scenenode;
			SpotLightComponent* spotlight;
		};

		SpotLightNode();

		bool Create( Entity* entity );

		bool GetPointers( EntitySystem& entity_system, Pointers& pointers );

		unsigned int GetEntityId();

		unsigned int GetSceneNodeComponentId() const;

		unsigned int GetSpotLightComponentId() const;

	private:

		unsigned int _entity_id;

		unsigned int _scenenode_id;
		unsigned int _spotlight_id;
};

}
}

#endif
