/*
	This file is automatically generated.
	Do not edit this file manually.
*/

#ifndef _SYSTEMNODESCONTAINER_HPP_
#define _SYSTEMNODESCONTAINER_HPP_

#include "SystemNodes.hpp"
#include "../../GameComponentInterfaces/Include/IWorld.hpp"

#include <list>

namespace rapidxml
{
	template<class Ch>
	class xml_node;
};

namespace Fnd
{
namespace EntitySystem
{

class SystemNodesContainer
{
	public:

	std::list<AmbientLightNode>& GetAmbientLightNodeList();
	const std::list<AmbientLightNode>& GetAmbientLightNodeList() const;

	std::list<CameraNode>& GetCameraNodeList();
	const std::list<CameraNode>& GetCameraNodeList() const;

	std::list<DirectionalLightNode>& GetDirectionalLightNodeList();
	const std::list<DirectionalLightNode>& GetDirectionalLightNodeList() const;

	std::list<ModelNode>& GetModelNodeList();
	const std::list<ModelNode>& GetModelNodeList() const;

	std::list<RigidBodyNode>& GetRigidBodyNodeList();
	const std::list<RigidBodyNode>& GetRigidBodyNodeList() const;

	std::list<PointLightNode>& GetPointLightNodeList();
	const std::list<PointLightNode>& GetPointLightNodeList() const;

	std::list<PostProcessNode>& GetPostProcessNodeList();
	const std::list<PostProcessNode>& GetPostProcessNodeList() const;

	std::list<RumbleNode>& GetRumbleNodeList();
	const std::list<RumbleNode>& GetRumbleNodeList() const;

	std::list<SceneNodeNode>& GetSceneNodeNodeList();
	const std::list<SceneNodeNode>& GetSceneNodeNodeList() const;

	std::list<ShadowCasterNode>& GetShadowCasterNodeList();
	const std::list<ShadowCasterNode>& GetShadowCasterNodeList() const;

	std::list<ShadowedSpotLightNode>& GetShadowedSpotLightNodeList();
	const std::list<ShadowedSpotLightNode>& GetShadowedSpotLightNodeList() const;

	std::list<SkyBoxNode>& GetSkyBoxNodeList();
	const std::list<SkyBoxNode>& GetSkyBoxNodeList() const;

	std::list<SpotLightNode>& GetSpotLightNodeList();
	const std::list<SpotLightNode>& GetSpotLightNodeList() const;

	private:

	std::list<AmbientLightNode> _ambientlightnode;
	std::list<CameraNode> _cameranode;
	std::list<DirectionalLightNode> _directionallightnode;
	std::list<ModelNode> _modelnode;
	std::list<RigidBodyNode> _rigidbodynode;
	std::list<PointLightNode> _pointlightnode;
	std::list<PostProcessNode> _postprocessnode;
	std::list<RumbleNode> _rumblenode;
	std::list<SceneNodeNode> _scenenodenode;
	std::list<ShadowCasterNode> _shadowcasternode;
	std::list<ShadowedSpotLightNode> _shadowedspotlightnode;
	std::list<SkyBoxNode> _skyboxnode;
	std::list<SpotLightNode> _spotlightnode;
};

}
}

#endif
