/*
	This file is automatically generated.
	Do not edit this file manually.
*/

#include "../Include/ComponentMaps.hpp"

using namespace Fnd::EntitySystem;

ComponentMaps::ComponentMaps()
{
}

Component* ComponentMaps::GetComponent( unsigned int component_id, unsigned int index )
{
	switch (component_id)
	{
		case 0:
			return GetComponent<SceneNodeComponent>(index);
		case 1:
			return GetComponent<CameraPropertiesComponent>(index);
		case 2:
			return GetComponent<RumbleComponent>(index);
		case 3:
			return GetComponent<RigidBodyComponent>(index);
		case 4:
			return GetComponent<AmbientLightComponent>(index);
		case 5:
			return GetComponent<DirectionalLightComponent>(index);
		case 6:
			return GetComponent<SpotLightComponent>(index);
		case 7:
			return GetComponent<PointLightComponent>(index);
		case 8:
			return GetComponent<ModelComponent>(index);
		case 9:
			return GetComponent<SkyBoxComponent>(index);
		case 10:
			return GetComponent<MotionBlurComponent>(index);
		case 11:
			return GetComponent<BloomComponent>(index);
		case 12:
			return GetComponent<ToneMapComponent>(index);
		case 13:
			return GetComponent<AmbientOcclusionComponent>(index);
		default:
			return nullptr;
}
}

